PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE voters(
ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
EMAIL TEXT NOT NULL,
NIF TEXT NOT NULL,
STATION_POLLING_NUMBER INT NOT NULL);
COMMIT;
